## <font color = green> Numpy Tutotrail </font>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

#### to create numpy array from a list

In [28]:
arr =np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### type of the array

In [30]:
type(arr)

numpy.ndarray

#### shape of the array

In [32]:
arr.shape

(9,)

#### dimension of the array

In [34]:
arr.ndim

1

#### to generate random integer

In [36]:
arr2 = np.random.randint(1,100,(5,5))
arr2

array([[56, 39, 38, 95, 83],
       [65, 18, 32, 81, 67],
       [72, 82, 64, 43, 23],
       [39, 32, 78, 69, 21],
       [66, 35, 56, 64, 84]])

In [37]:
arr2.shape

(5, 5)

In [38]:
arr2.ndim

2

#### to create a matrics or array with all values 0

In [53]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### to create a matrics or vector with all the values 1

In [57]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### to create a diagonal matrix or vector 

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### to create a matrics with all vlaues the same number

In [69]:
np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

#### to generate numbers with fixed gap

In [6]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

#### to generate values wich are evenly spaced

In [76]:
np.linspace(2,20,4)

array([ 2.,  8., 14., 20.])

#### Numpy operations

In [37]:
np.random.seed(42)
a = np.random.randint(0,20,(5,4))
b = np.random.randint(0,20,(5,4))


In [45]:
print(a)
print("=============")
print(b)

[[ 6 19 14 10]
 [ 7  6 18 10]
 [10  3  7  2]
 [ 1 11  5  1]
 [ 0 11 11 16]]
[[ 9 15 14 14]
 [18 11 19  2]
 [ 4 18  6  8]
 [ 6 17  3 13]
 [17  8  1 19]]


#### operations using operators

In [43]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[15 34 28 24]
 [25 17 37 12]
 [14 21 13 10]
 [ 7 28  8 14]
 [17 19 12 35]]
[[ -3   4   0  -4]
 [-11  -5  -1   8]
 [  6 -15   1  -6]
 [ -5  -6   2 -12]
 [-17   3  10  -3]]
[[ 54 285 196 140]
 [126  66 342  20]
 [ 40  54  42  16]
 [  6 187  15  13]
 [  0  88  11 304]]
[[ 0.66666667  1.26666667  1.          0.71428571]
 [ 0.38888889  0.54545455  0.94736842  5.        ]
 [ 2.5         0.16666667  1.16666667  0.25      ]
 [ 0.16666667  0.64705882  1.66666667  0.07692308]
 [ 0.          1.375      11.          0.84210526]]


#### operations using atributes

In [57]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 34 28 24]
 [25 17 37 12]
 [14 21 13 10]
 [ 7 28  8 14]
 [17 19 12 35]]
[[ -3   4   0  -4]
 [-11  -5  -1   8]
 [  6 -15   1  -6]
 [ -5  -6   2 -12]
 [-17   3  10  -3]]
[[ 54 285 196 140]
 [126  66 342  20]
 [ 40  54  42  16]
 [  6 187  15  13]
 [  0  88  11 304]]
[[ 0.66666667  1.26666667  1.          0.71428571]
 [ 0.38888889  0.54545455  0.94736842  5.        ]
 [ 2.5         0.16666667  1.16666667  0.25      ]
 [ 0.16666667  0.64705882  1.66666667  0.07692308]
 [ 0.          1.375      11.          0.84210526]]


#### Array transpose

#### using transpose method

In [60]:
trans = np.transpose(a)
print(trans)

[[ 6  7 10  1  0]
 [19  6  3 11 11]
 [14 18  7  5 11]
 [10 10  2  1 16]]


In [64]:
print(a.shape)
print(trans.shape)

(5, 4)
(4, 5)


#### using .T atribute

In [68]:
trans2 = a.T
print(trans2)


[[ 6  7 10  1  0]
 [19  6  3 11 11]
 [14 18  7  5 11]
 [10 10  2  1 16]]


In [70]:
trans2.shape

(4, 5)

#### Array reshaping

In [77]:
areshaped = a.reshape(10,2)
areshaped

array([[ 6, 19],
       [14, 10],
       [ 7,  6],
       [18, 10],
       [10,  3],
       [ 7,  2],
       [ 1, 11],
       [ 5,  1],
       [ 0, 11],
       [11, 16]])

In [79]:
areshaped.shape

(10, 2)

In [85]:
df = pd.read_csv("creditcard.csv")

In [86]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

#### to create a sample from the dataframe randomly

In [100]:
np.random.seed(42) ## prvent from generating random values every time we run the code
rand_df = pd.DataFrame(np.random.rand(20,10))
rand_df

0         1         2         3         4         5         6  \
0   0.374540  0.950714  0.731994  0.598658  0.156019  0.155995  0.058084   
1   0.020584  0.969910  0.832443  0.212339  0.181825  0.183405  0.304242   
2   0.611853  0.139494  0.292145  0.366362  0.456070  0.785176  0.199674   
3   0.607545  0.170524  0.065052  0.948886  0.965632  0.808397  0.304614   
4   0.122038  0.495177  0.034389  0.909320  0.258780  0.662522  0.311711   
5   0.969585  0.775133  0.939499  0.894827  0.597900  0.921874  0.088493   
6   0.388677  0.271349  0.828738  0.356753  0.280935  0.542696  0.140924   
7   0.772245  0.198716  0.005522  0.815461  0.706857  0.729007  0.771270   
8   0.863103  0.623298  0.330898  0.063558  0.310982  0.325183  0.729606   
9   0.119594  0.713245  0.760785  0.561277  0.770967  0.493796  0.522733   
10  0.031429  0.636410  0.314356  0.508571  0.907566  0.249292  0.410383   
11  0.289751  0.161221  0.929698  0.808120  0.633404  0.871461  0.803672   
12  0.807440  0.896091  0.318003  0.110052  0.227935  0.427108  0.818015   
13  0.417411  0.222108  0.119865  0.337615  0.942910  0.323203  0.518791   
14  0.962447  0.251782  0.497249  0.300878  0.284840  0.036887  0.609564   
15  0.908266  0.239562  0.144895  0.489453  0.985650  0.242055  0.672136   
16  0.367783  0.632306  0.633530  0.535775  0.090290  0.835302  0.320780   
17  0.677564  0.016588  0.512093  0.226496  0.645173  0.174366  0.690938   
18  0.341066  0.113474  0.924694  0.877339  0.257942  0.659984  0.817222   
19  0.093103  0.897216  0.900418  0.633101  0.339030  0.349210  0.725956   

           7         8         9  
0   0.866176  0.601115  0.708073  
1   0.524756  0.431945  0.291229  
2   0.514234  0.592415  0.046450  
3   0.097672  0.684233  0.440152  
4   0.520068  0.546710  0.184854  
5   0.195983  0.045227  0.325330  
6   0.802197  0.074551  0.986887  
7   0.074045  0.358466  0.115869  
8   0.637557  0.887213  0.472215  
9   0.427541  0.025419  0.107891  
10  0.755551  0.228798  0.076980  
11  0.186570  0.892559  0.539342  
12  0.860731  0.006952  0.510747  
13  0.703019  0.363630  0.971782  
14  0.502679  0.051479  0.278646  
15  0.761620  0.237638  0.728216  
16  0.186519  0.040775  0.590893  
17  0.386735  0.936730  0.137521  
18  0.555201  0.529651  0.241852  
19  0.897110  0.887086  0.779876